### ISSUE TITLE
Dialyzer warnings when BiMap is used as a module attribute

### ISSUE THREAD

**Issue by bblaszkow06** [mkaput/elixir-bimap#40]
When BiMap is used as a module attribute, e.g.
```elixir
defmodule Example do
  @attr BiMap.new(%{1 => :a})
end
```
the dialyzer complains about the use of opaque type. Although it is correct (if both the implementation of `new` and the internal representation change, until recompilation the beam file will contain the old representation) it hinders the usability.

One way to solve that would be to follow Elixir's steps with MapSet https://github.com/elixir-lang/elixir/pull/11917 making the top-level struct keys public and limit "opaqueness" to the values. WDYT about it?

**Comment by mkaput** [comment]
That makes sense!

**Comment by mkaput** [comment]
fixed in https://github.com/mkaput/elixir-bimap/commit/62b34162f13485461bc263a9ed493bf00030ae5e
